name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Automated tests
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: github_actions_testing_test
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
    - uses: actions/checkout@v1
    - name: Build application
      run: make github
    - name: Lint with PHP CS Fixer
      run: make lint
    - name: Test with PHPUnit
      run: make test
